// Mocks generated by Mockito 5.4.6 from annotations
// in world_soccer/test/service/chat_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:world_soccer/repo/chat_repo.dart' as _i3;
import 'package:world_soccer/types/chat.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatRoom_0 extends _i1.SmartFake implements _i2.ChatRoom {
  _FakeChatRoom_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatMessage_1 extends _i1.SmartFake implements _i2.ChatMessage {
  _FakeChatMessage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepo extends _i1.Mock implements _i3.ChatRepo {
  MockChatRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ChatRoom>> getMyRooms(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyRooms, [playerId]),
            returnValue: _i4.Future<List<_i2.ChatRoom>>.value(<_i2.ChatRoom>[]),
          )
          as _i4.Future<List<_i2.ChatRoom>>);

  @override
  _i4.Future<_i2.ChatRoom> getRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoom, [roomId]),
            returnValue: _i4.Future<_i2.ChatRoom>.value(
              _FakeChatRoom_0(this, Invocation.method(#getRoom, [roomId])),
            ),
          )
          as _i4.Future<_i2.ChatRoom>);

  @override
  _i4.Future<bool> isMember({
    required String? roomId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isMember, [], {
              #roomId: roomId,
              #playerId: playerId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.ChatRoom> getOrCreateDirectRoom({
    required String? meId,
    required String? otherId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateDirectRoom, [], {
              #meId: meId,
              #otherId: otherId,
            }),
            returnValue: _i4.Future<_i2.ChatRoom>.value(
              _FakeChatRoom_0(
                this,
                Invocation.method(#getOrCreateDirectRoom, [], {
                  #meId: meId,
                  #otherId: otherId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChatRoom>);

  @override
  _i4.Future<List<_i2.ChatMessage>> getMessages(
    String? roomId, {
    int? limit = 50,
    DateTime? before,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [roomId],
              {#limit: limit, #before: before},
            ),
            returnValue: _i4.Future<List<_i2.ChatMessage>>.value(
              <_i2.ChatMessage>[],
            ),
          )
          as _i4.Future<List<_i2.ChatMessage>>);

  @override
  _i4.Future<_i2.ChatMessage> sendMessage({
    required String? roomId,
    required String? senderId,
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #roomId: roomId,
              #senderId: senderId,
              #text: text,
            }),
            returnValue: _i4.Future<_i2.ChatMessage>.value(
              _FakeChatMessage_1(
                this,
                Invocation.method(#sendMessage, [], {
                  #roomId: roomId,
                  #senderId: senderId,
                  #text: text,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChatMessage>);

  @override
  _i4.Future<void> markAsRead({
    required String? roomId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [], {
              #roomId: roomId,
              #playerId: playerId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.ChatMessage> subscribeMessages(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeMessages, [roomId]),
            returnValue: _i4.Stream<_i2.ChatMessage>.empty(),
          )
          as _i4.Stream<_i2.ChatMessage>);
}
