// Mocks generated by Mockito 5.4.6 from annotations
// in world_soccer/test/service/lineup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:world_soccer/repo/lineup_repo.dart' as _i3;
import 'package:world_soccer/repo/player_repo.dart' as _i5;
import 'package:world_soccer/types/enums.dart' as _i6;
import 'package:world_soccer/types/match.dart' as _i7;
import 'package:world_soccer/types/player.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlayer_0 extends _i1.SmartFake implements _i2.Player {
  _FakePlayer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LineupRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLineupRepo extends _i1.Mock implements _i3.LineupRepo {
  MockLineupRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
    Map<int, ({String formationName, Map<int, String> slotToPlayerId})>
  >
  getByMatch(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#getByMatch, [matchId]),
            returnValue:
                _i4.Future<
                  Map<
                    int,
                    ({String formationName, Map<int, String> slotToPlayerId})
                  >
                >.value(
                  <
                    int,
                    ({String formationName, Map<int, String> slotToPlayerId})
                  >{},
                ),
          )
          as _i4.Future<
            Map<int, ({String formationName, Map<int, String> slotToPlayerId})>
          >);

  @override
  _i4.Future<void> save({
    required String? matchId,
    required Map<
      int,
      ({String formationName, Map<int, String> slotToPlayerId})
    >?
    quarters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#save, [], {
              #matchId: matchId,
              #quarters: quarters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearQuarter({
    required String? matchId,
    required int? quarter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearQuarter, [], {
              #matchId: matchId,
              #quarter: quarter,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PlayerRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepo extends _i1.Mock implements _i5.PlayerRepo {
  MockPlayerRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Player> getById(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [playerId]),
            returnValue: _i4.Future<_i2.Player>.value(
              _FakePlayer_0(this, Invocation.method(#getById, [playerId])),
            ),
          )
          as _i4.Future<_i2.Player>);

  @override
  _i4.Future<void> setActiveTeam({
    required String? playerId,
    required String? teamId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveTeam, [], {
              #playerId: playerId,
              #teamId: teamId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getActiveTeamId(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTeamId, [playerId]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> joinMatch({
    required String? matchId,
    required String? playerId,
    required List<_i6.Position>? preferredPositions,
    required List<int>? availableQuarters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinMatch, [], {
              #matchId: matchId,
              #playerId: playerId,
              #preferredPositions: preferredPositions,
              #availableQuarters: availableQuarters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> leaveMatch({
    required String? matchId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveMatch, [], {
              #matchId: matchId,
              #playerId: playerId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.MatchParticipation>> getParticipations(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#getParticipations, [matchId]),
            returnValue: _i4.Future<List<_i7.MatchParticipation>>.value(
              <_i7.MatchParticipation>[],
            ),
          )
          as _i4.Future<List<_i7.MatchParticipation>>);
}
