// Mocks generated by Mockito 5.4.6 from annotations
// in world_soccer/test/service/match_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:world_soccer/repo/match_repo.dart' as _i4;
import 'package:world_soccer/repo/player_repo.dart' as _i6;
import 'package:world_soccer/types/enums.dart' as _i7;
import 'package:world_soccer/types/match.dart' as _i2;
import 'package:world_soccer/types/player.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMatch_0 extends _i1.SmartFake implements _i2.Match {
  _FakeMatch_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayer_1 extends _i1.SmartFake implements _i3.Player {
  _FakePlayer_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MatchRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchRepo extends _i1.Mock implements _i4.MatchRepo {
  MockMatchRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Match>> getByTeam(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getByTeam, [teamId]),
            returnValue: _i5.Future<List<_i2.Match>>.value(<_i2.Match>[]),
          )
          as _i5.Future<List<_i2.Match>>);

  @override
  _i5.Future<_i2.Match> getById(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [matchId]),
            returnValue: _i5.Future<_i2.Match>.value(
              _FakeMatch_0(this, Invocation.method(#getById, [matchId])),
            ),
          )
          as _i5.Future<_i2.Match>);

  @override
  _i5.Future<_i2.Match> create({
    required String? teamId,
    required DateTime? date,
    required String? location,
    required String? opponentName,
    String? opponentLogoUrl,
    int? durationMinutes = 120,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #teamId: teamId,
              #date: date,
              #location: location,
              #opponentName: opponentName,
              #opponentLogoUrl: opponentLogoUrl,
              #durationMinutes: durationMinutes,
            }),
            returnValue: _i5.Future<_i2.Match>.value(
              _FakeMatch_0(
                this,
                Invocation.method(#create, [], {
                  #teamId: teamId,
                  #date: date,
                  #location: location,
                  #opponentName: opponentName,
                  #opponentLogoUrl: opponentLogoUrl,
                  #durationMinutes: durationMinutes,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Match>);

  @override
  _i5.Future<void> updateResult({
    required String? matchId,
    required int? ourScore,
    required int? opponentScore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateResult, [], {
              #matchId: matchId,
              #ourScore: ourScore,
              #opponentScore: opponentScore,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateInfo({
    required String? matchId,
    DateTime? date,
    String? location,
    String? opponentName,
    int? durationMinutes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateInfo, [], {
              #matchId: matchId,
              #date: date,
              #location: location,
              #opponentName: opponentName,
              #durationMinutes: durationMinutes,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateStatus({
    required String? matchId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [], {
              #matchId: matchId,
              #status: status,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [matchId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Match>> getH2H({
    required String? teamId,
    required String? opponentName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getH2H, [], {
              #teamId: teamId,
              #opponentName: opponentName,
            }),
            returnValue: _i5.Future<List<_i2.Match>>.value(<_i2.Match>[]),
          )
          as _i5.Future<List<_i2.Match>>);
}

/// A class which mocks [PlayerRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepo extends _i1.Mock implements _i6.PlayerRepo {
  MockPlayerRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Player> getById(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [playerId]),
            returnValue: _i5.Future<_i3.Player>.value(
              _FakePlayer_1(this, Invocation.method(#getById, [playerId])),
            ),
          )
          as _i5.Future<_i3.Player>);

  @override
  _i5.Future<void> setActiveTeam({
    required String? playerId,
    required String? teamId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveTeam, [], {
              #playerId: playerId,
              #teamId: teamId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getActiveTeamId(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTeamId, [playerId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> joinMatch({
    required String? matchId,
    required String? playerId,
    required List<_i7.Position>? preferredPositions,
    required List<int>? availableQuarters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinMatch, [], {
              #matchId: matchId,
              #playerId: playerId,
              #preferredPositions: preferredPositions,
              #availableQuarters: availableQuarters,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveMatch({
    required String? matchId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveMatch, [], {
              #matchId: matchId,
              #playerId: playerId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.MatchParticipation>> getParticipations(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#getParticipations, [matchId]),
            returnValue: _i5.Future<List<_i2.MatchParticipation>>.value(
              <_i2.MatchParticipation>[],
            ),
          )
          as _i5.Future<List<_i2.MatchParticipation>>);
}
