// Mocks generated by Mockito 5.4.6 from annotations
// in world_soccer/test/service/team_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:world_soccer/repo/player_repo.dart' as _i7;
import 'package:world_soccer/repo/team_repo.dart' as _i4;
import 'package:world_soccer/types/enums.dart' as _i8;
import 'package:world_soccer/types/match.dart' as _i9;
import 'package:world_soccer/types/player.dart' as _i3;
import 'package:world_soccer/types/team.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTeam_0 extends _i1.SmartFake implements _i2.Team {
  _FakeTeam_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTeamStats_1 extends _i1.SmartFake implements _i2.TeamStats {
  _FakeTeamStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayer_2 extends _i1.SmartFake implements _i3.Player {
  _FakePlayer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TeamRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamRepo extends _i1.Mock implements _i4.TeamRepo {
  MockTeamRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Team>> getMyTeams(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyTeams, [playerId]),
            returnValue: _i5.Future<List<_i2.Team>>.value(<_i2.Team>[]),
          )
          as _i5.Future<List<_i2.Team>>);

  @override
  _i5.Future<_i2.Team> getById(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [teamId]),
            returnValue: _i5.Future<_i2.Team>.value(
              _FakeTeam_0(this, Invocation.method(#getById, [teamId])),
            ),
          )
          as _i5.Future<_i2.Team>);

  @override
  _i5.Future<List<_i2.TeamMember>> getMembers(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, [teamId]),
            returnValue: _i5.Future<List<_i2.TeamMember>>.value(
              <_i2.TeamMember>[],
            ),
          )
          as _i5.Future<List<_i2.TeamMember>>);

  @override
  _i5.Future<_i2.Team> create({
    required String? name,
    String? logoUrl,
    String? logoColor,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #name: name,
              #logoUrl: logoUrl,
              #logoColor: logoColor,
              #description: description,
            }),
            returnValue: _i5.Future<_i2.Team>.value(
              _FakeTeam_0(
                this,
                Invocation.method(#create, [], {
                  #name: name,
                  #logoUrl: logoUrl,
                  #logoColor: logoColor,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Team>);

  @override
  _i5.Future<_i2.Team> updateInfo({
    required String? teamId,
    String? name,
    String? logoUrl,
    String? logoColor,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateInfo, [], {
              #teamId: teamId,
              #name: name,
              #logoUrl: logoUrl,
              #logoColor: logoColor,
              #description: description,
            }),
            returnValue: _i5.Future<_i2.Team>.value(
              _FakeTeam_0(
                this,
                Invocation.method(#updateInfo, [], {
                  #teamId: teamId,
                  #name: name,
                  #logoUrl: logoUrl,
                  #logoColor: logoColor,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Team>);

  @override
  _i5.Future<void> join({required String? teamId, required String? playerId}) =>
      (super.noSuchMethod(
            Invocation.method(#join, [], {
              #teamId: teamId,
              #playerId: playerId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leave({
    required String? teamId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leave, [], {
              #teamId: teamId,
              #playerId: playerId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> uploadLogo({
    required String? teamId,
    required List<int>? bytes,
    required String? extension,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadLogo, [], {
              #teamId: teamId,
              #bytes: bytes,
              #extension: extension,
            }),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadLogo, [], {
                  #teamId: teamId,
                  #bytes: bytes,
                  #extension: extension,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i2.TeamStats> getStats(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getStats, [teamId]),
            returnValue: _i5.Future<_i2.TeamStats>.value(
              _FakeTeamStats_1(this, Invocation.method(#getStats, [teamId])),
            ),
          )
          as _i5.Future<_i2.TeamStats>);

  @override
  _i5.Future<String> createInviteCode({
    required String? teamId,
    String? role = 'member',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInviteCode, [], {
              #teamId: teamId,
              #role: role,
            }),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createInviteCode, [], {
                  #teamId: teamId,
                  #role: role,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<Map<String, dynamic>> joinByInviteCode(String? inviteCode) =>
      (super.noSuchMethod(
            Invocation.method(#joinByInviteCode, [inviteCode]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [PlayerRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepo extends _i1.Mock implements _i7.PlayerRepo {
  MockPlayerRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Player> getById(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [playerId]),
            returnValue: _i5.Future<_i3.Player>.value(
              _FakePlayer_2(this, Invocation.method(#getById, [playerId])),
            ),
          )
          as _i5.Future<_i3.Player>);

  @override
  _i5.Future<void> setActiveTeam({
    required String? playerId,
    required String? teamId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveTeam, [], {
              #playerId: playerId,
              #teamId: teamId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getActiveTeamId(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveTeamId, [playerId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> joinMatch({
    required String? matchId,
    required String? playerId,
    required List<_i8.Position>? preferredPositions,
    required List<int>? availableQuarters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinMatch, [], {
              #matchId: matchId,
              #playerId: playerId,
              #preferredPositions: preferredPositions,
              #availableQuarters: availableQuarters,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveMatch({
    required String? matchId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#leaveMatch, [], {
              #matchId: matchId,
              #playerId: playerId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.MatchParticipation>> getParticipations(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#getParticipations, [matchId]),
            returnValue: _i5.Future<List<_i9.MatchParticipation>>.value(
              <_i9.MatchParticipation>[],
            ),
          )
          as _i5.Future<List<_i9.MatchParticipation>>);
}
